sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache/files

env:
  global:
    - COMPOSER_OPTIONS="--prefer-stable"

php:
  - 5.4
  - 5.5
  - 5.6

matrix:
  fast_finish: true
  include:
    - php: 5.3
      dist: precise
      env: COMPOSER_OPTIONS="--prefer-lowest --prefer-stable"
    - php: 7.0
      env: xdebug="yes" COMPOSER_OPTIONS=""

before_install:
  - if [[ "$xdebug" != "yes" ]]; then phpenv config-rm xdebug.ini; fi
  - composer self-update

install:
  - composer update $COMPOSER_OPTIONS

script:
  - vendor/bin/phpspec run
